// Code generated by girgen. DO NOT EDIT.

package lasem

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: lasem-0.7
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <lsm.h>
// #include <lsmdom.h>
// #include <lsmdomdocument.h>
// #include <lsmdomdocumentfragment.h>
// #include <lsmdomnamednodemap.h>
import "C"
