// Code generated by girgen. DO NOT EDIT.

package lasem

// #include <stdlib.h>
// #include <lsm.h>
// #include <lsmdom.h>
// #include <lsmdomdocument.h>
// #include <lsmdomdocumentfragment.h>
// #include <lsmdomnamednodemap.h>
import "C"

func Shutdown() {
	C.lsm_shutdown()
}
