// Code generated by girgen. DO NOT EDIT.

package lasem

// #include <stdlib.h>
// #include <lsm.h>
// #include <lsmdom.h>
// #include <lsmdomdocument.h>
// #include <lsmdomdocumentfragment.h>
// #include <lsmdomnamednodemap.h>
// #include <lsmmathmlactionelement.h>
// #include <lsmmathmlaligngroupelement.h>
// #include <lsmmathmlalignmarkelement.h>
// #include <lsmmathmlattributes.h>
// #include <lsmmathmldocument.h>
// #include <lsmmathmlelement.h>
// #include <lsmmathmlencloseelement.h>
// #include <lsmmathmlenums.h>
// #include <lsmmathmlerrorelement.h>
// #include <lsmmathmlfencedelement.h>
// #include <lsmmathmlfractionelement.h>
// #include <lsmmathmlglyphtableams.h>
// #include <lsmmathmlitexelement.h>
// #include <lsmmathmllayoututils.h>
// #include <lsmmathmlmathelement.h>
// #include <lsmmathmloperatordictionary.h>
// #include <lsmmathmloperatorelement.h>
// #include <lsmmathmlpaddedelement.h>
// #include <lsmmathmlphantomelement.h>
// #include <lsmmathmlpresentationcontainer.h>
// #include <lsmmathmlpresentationtoken.h>
// #include <lsmmathmlradicalelement.h>
// #include <lsmmathmlrowelement.h>
// #include <lsmmathmlscriptelement.h>
// #include <lsmmathmlsemanticselement.h>
// #include <lsmmathmlspaceelement.h>
// #include <lsmmathmlstringelement.h>
// #include <lsmmathmlstyle.h>
// #include <lsmmathmlstyleelement.h>
// #include <lsmmathmltablecellelement.h>
// #include <lsmmathmltableelement.h>
// #include <lsmmathmltablerowelement.h>
// #include <lsmmathmltraits.h>
// #include <lsmmathmlunderoverelement.h>
// #include <lsmmathmlutils.h>
// #include <lsmmathmlview.h>
// #include <lsmsvgaelement.h>
// #include <lsmsvgattributes.h>
// #include <lsmsvgcircleelement.h>
// #include <lsmsvgclippathelement.h>
// #include <lsmsvgcolors.h>
// #include <lsmsvgdefselement.h>
// #include <lsmsvgdocument.h>
// #include <lsmsvgelement.h>
// #include <lsmsvgellipseelement.h>
// #include <lsmsvgenums.h>
// #include <lsmsvgfilterblend.h>
// #include <lsmsvgfiltercolormatrix.h>
// #include <lsmsvgfiltercomposite.h>
// #include <lsmsvgfilterconvolvematrix.h>
// #include <lsmsvgfilterdisplacementmap.h>
// #include <lsmsvgfilterelement.h>
// #include <lsmsvgfilterflood.h>
// #include <lsmsvgfiltergaussianblur.h>
// #include <lsmsvgfilterimage.h>
// #include <lsmsvgfiltermerge.h>
// #include <lsmsvgfiltermergenode.h>
// #include <lsmsvgfiltermorphology.h>
// #include <lsmsvgfilteroffset.h>
// #include <lsmsvgfilterprimitive.h>
// #include <lsmsvgfilterspecularlighting.h>
// #include <lsmsvgfiltersurface.h>
// #include <lsmsvgfiltertile.h>
// #include <lsmsvgfilterturbulence.h>
// #include <lsmsvggelement.h>
// #include <lsmsvggradientelement.h>
// #include <lsmsvgimageelement.h>
// #include <lsmsvglength.h>
// #include <lsmsvglineargradientelement.h>
// #include <lsmsvglineelement.h>
// #include <lsmsvgmarkerelement.h>
// #include <lsmsvgmaskelement.h>
// #include <lsmsvgmatrix.h>
// #include <lsmsvgpathelement.h>
// #include <lsmsvgpatternelement.h>
// #include <lsmsvgpolygonelement.h>
// #include <lsmsvgpolylineelement.h>
// #include <lsmsvgradialgradientelement.h>
// #include <lsmsvgrectelement.h>
// #include <lsmsvgstopelement.h>
// #include <lsmsvgstyle.h>
// #include <lsmsvgsvgelement.h>
// #include <lsmsvgswitchelement.h>
// #include <lsmsvgsymbolelement.h>
// #include <lsmsvgtextelement.h>
// #include <lsmsvgtraits.h>
// #include <lsmsvgtransformable.h>
// #include <lsmsvgtspanelement.h>
// #include <lsmsvguseelement.h>
// #include <lsmsvgview.h>
import "C"

// SVGColorProperty: instance of this type is always passed by reference.
type SVGColorProperty struct {
	*svgColorProperty
}

// svgColorProperty is the struct that's finalized.
type svgColorProperty struct {
	native *C.LsmSvgColorProperty
}

// SVGCompOpProperty: instance of this type is always passed by reference.
type SVGCompOpProperty struct {
	*svgCompOpProperty
}

// svgCompOpProperty is the struct that's finalized.
type svgCompOpProperty struct {
	native *C.LsmSvgCompOpProperty
}

// SVGDashArrayProperty: instance of this type is always passed by reference.
type SVGDashArrayProperty struct {
	*svgDashArrayProperty
}

// svgDashArrayProperty is the struct that's finalized.
type svgDashArrayProperty struct {
	native *C.LsmSvgDashArrayProperty
}

// SVGDisplayProperty: instance of this type is always passed by reference.
type SVGDisplayProperty struct {
	*svgDisplayProperty
}

// svgDisplayProperty is the struct that's finalized.
type svgDisplayProperty struct {
	native *C.LsmSvgDisplayProperty
}

// SVGDoubleProperty: instance of this type is always passed by reference.
type SVGDoubleProperty struct {
	*svgDoubleProperty
}

// svgDoubleProperty is the struct that's finalized.
type svgDoubleProperty struct {
	native *C.LsmSvgDoubleProperty
}

// SVGEnableBackgroundProperty: instance of this type is always passed by
// reference.
type SVGEnableBackgroundProperty struct {
	*svgEnableBackgroundProperty
}

// svgEnableBackgroundProperty is the struct that's finalized.
type svgEnableBackgroundProperty struct {
	native *C.LsmSvgEnableBackgroundProperty
}

// SVGFillRuleProperty: instance of this type is always passed by reference.
type SVGFillRuleProperty struct {
	*svgFillRuleProperty
}

// svgFillRuleProperty is the struct that's finalized.
type svgFillRuleProperty struct {
	native *C.LsmSvgFillRuleProperty
}

// SVGFontStretchProperty: instance of this type is always passed by reference.
type SVGFontStretchProperty struct {
	*svgFontStretchProperty
}

// svgFontStretchProperty is the struct that's finalized.
type svgFontStretchProperty struct {
	native *C.LsmSvgFontStretchProperty
}

// SVGFontStyleProperty: instance of this type is always passed by reference.
type SVGFontStyleProperty struct {
	*svgFontStyleProperty
}

// svgFontStyleProperty is the struct that's finalized.
type svgFontStyleProperty struct {
	native *C.LsmSvgFontStyleProperty
}

// SVGFontWeightProperty: instance of this type is always passed by reference.
type SVGFontWeightProperty struct {
	*svgFontWeightProperty
}

// svgFontWeightProperty is the struct that's finalized.
type svgFontWeightProperty struct {
	native *C.LsmSvgFontWeightProperty
}

// SVGLengthProperty: instance of this type is always passed by reference.
type SVGLengthProperty struct {
	*svgLengthProperty
}

// svgLengthProperty is the struct that's finalized.
type svgLengthProperty struct {
	native *C.LsmSvgLengthProperty
}

// SVGLineCapProperty: instance of this type is always passed by reference.
type SVGLineCapProperty struct {
	*svgLineCapProperty
}

// svgLineCapProperty is the struct that's finalized.
type svgLineCapProperty struct {
	native *C.LsmSvgLineCapProperty
}

// SVGLineJoinProperty: instance of this type is always passed by reference.
type SVGLineJoinProperty struct {
	*svgLineJoinProperty
}

// svgLineJoinProperty is the struct that's finalized.
type svgLineJoinProperty struct {
	native *C.LsmSvgLineJoinProperty
}

// SVGOverflowProperty: instance of this type is always passed by reference.
type SVGOverflowProperty struct {
	*svgOverflowProperty
}

// svgOverflowProperty is the struct that's finalized.
type svgOverflowProperty struct {
	native *C.LsmSvgOverflowProperty
}

// SVGPaintProperty: instance of this type is always passed by reference.
type SVGPaintProperty struct {
	*svgPaintProperty
}

// svgPaintProperty is the struct that's finalized.
type svgPaintProperty struct {
	native *C.LsmSvgPaintProperty
}

// SVGStyle: instance of this type is always passed by reference.
type SVGStyle struct {
	*svgStyle
}

// svgStyle is the struct that's finalized.
type svgStyle struct {
	native *C.LsmSvgStyle
}

// SVGTextAnchorProperty: instance of this type is always passed by reference.
type SVGTextAnchorProperty struct {
	*svgTextAnchorProperty
}

// svgTextAnchorProperty is the struct that's finalized.
type svgTextAnchorProperty struct {
	native *C.LsmSvgTextAnchorProperty
}

// SVGTransformProperty: instance of this type is always passed by reference.
type SVGTransformProperty struct {
	*svgTransformProperty
}

// svgTransformProperty is the struct that's finalized.
type svgTransformProperty struct {
	native *C.LsmSvgTransformProperty
}

// SVGVisibilityProperty: instance of this type is always passed by reference.
type SVGVisibilityProperty struct {
	*svgVisibilityProperty
}

// svgVisibilityProperty is the struct that's finalized.
type svgVisibilityProperty struct {
	native *C.LsmSvgVisibilityProperty
}

// SVGWritingModeProperty: instance of this type is always passed by reference.
type SVGWritingModeProperty struct {
	*svgWritingModeProperty
}

// svgWritingModeProperty is the struct that's finalized.
type svgWritingModeProperty struct {
	native *C.LsmSvgWritingModeProperty
}
