// Code generated by girgen. DO NOT EDIT.

package lasem

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <lsm.h>
// #include <lsmdom.h>
// #include <lsmdomdocument.h>
// #include <lsmdomdocumentfragment.h>
// #include <lsmdomnamednodemap.h>
// #include <lsmmathmlactionelement.h>
// #include <lsmmathmlaligngroupelement.h>
// #include <lsmmathmlalignmarkelement.h>
// #include <lsmmathmlattributes.h>
// #include <lsmmathmldocument.h>
// #include <lsmmathmlelement.h>
// #include <lsmmathmlencloseelement.h>
// #include <lsmmathmlenums.h>
// #include <lsmmathmlerrorelement.h>
// #include <lsmmathmlfencedelement.h>
// #include <lsmmathmlfractionelement.h>
// #include <lsmmathmlglyphtableams.h>
// #include <lsmmathmlitexelement.h>
// #include <lsmmathmllayoututils.h>
// #include <lsmmathmlmathelement.h>
// #include <lsmmathmloperatordictionary.h>
// #include <lsmmathmloperatorelement.h>
// #include <lsmmathmlpaddedelement.h>
// #include <lsmmathmlphantomelement.h>
// #include <lsmmathmlpresentationcontainer.h>
// #include <lsmmathmlpresentationtoken.h>
// #include <lsmmathmlradicalelement.h>
// #include <lsmmathmlrowelement.h>
// #include <lsmmathmlscriptelement.h>
// #include <lsmmathmlsemanticselement.h>
// #include <lsmmathmlspaceelement.h>
// #include <lsmmathmlstringelement.h>
// #include <lsmmathmlstyle.h>
// #include <lsmmathmlstyleelement.h>
// #include <lsmmathmltablecellelement.h>
// #include <lsmmathmltableelement.h>
// #include <lsmmathmltablerowelement.h>
// #include <lsmmathmltraits.h>
// #include <lsmmathmlunderoverelement.h>
// #include <lsmmathmlutils.h>
// #include <lsmmathmlview.h>
// #include <lsmsvgaelement.h>
// #include <lsmsvgattributes.h>
// #include <lsmsvgcircleelement.h>
// #include <lsmsvgclippathelement.h>
// #include <lsmsvgcolors.h>
// #include <lsmsvgdefselement.h>
// #include <lsmsvgdocument.h>
// #include <lsmsvgelement.h>
// #include <lsmsvgellipseelement.h>
// #include <lsmsvgenums.h>
// #include <lsmsvgfilterblend.h>
// #include <lsmsvgfiltercolormatrix.h>
// #include <lsmsvgfiltercomposite.h>
// #include <lsmsvgfilterconvolvematrix.h>
// #include <lsmsvgfilterdisplacementmap.h>
// #include <lsmsvgfilterelement.h>
// #include <lsmsvgfilterflood.h>
// #include <lsmsvgfiltergaussianblur.h>
// #include <lsmsvgfilterimage.h>
// #include <lsmsvgfiltermerge.h>
// #include <lsmsvgfiltermergenode.h>
// #include <lsmsvgfiltermorphology.h>
// #include <lsmsvgfilteroffset.h>
// #include <lsmsvgfilterprimitive.h>
// #include <lsmsvgfilterspecularlighting.h>
// #include <lsmsvgfiltersurface.h>
// #include <lsmsvgfiltertile.h>
// #include <lsmsvgfilterturbulence.h>
// #include <lsmsvggelement.h>
// #include <lsmsvggradientelement.h>
// #include <lsmsvgimageelement.h>
// #include <lsmsvglength.h>
// #include <lsmsvglineargradientelement.h>
// #include <lsmsvglineelement.h>
// #include <lsmsvgmarkerelement.h>
// #include <lsmsvgmaskelement.h>
// #include <lsmsvgmatrix.h>
// #include <lsmsvgpathelement.h>
// #include <lsmsvgpatternelement.h>
// #include <lsmsvgpolygonelement.h>
// #include <lsmsvgpolylineelement.h>
// #include <lsmsvgradialgradientelement.h>
// #include <lsmsvgrectelement.h>
// #include <lsmsvgstopelement.h>
// #include <lsmsvgstyle.h>
// #include <lsmsvgsvgelement.h>
// #include <lsmsvgswitchelement.h>
// #include <lsmsvgsymbolelement.h>
// #include <lsmsvgtextelement.h>
// #include <lsmsvgtraits.h>
// #include <lsmsvgtransformable.h>
// #include <lsmsvgtspanelement.h>
// #include <lsmsvguseelement.h>
// #include <lsmsvgview.h>
// extern void _gotk4_lasem0_SvgFilterPrimitiveClass_apply(LsmSvgFilterPrimitive*, LsmSvgView*, char*, char*, LsmBox*);
import "C"

// glib.Type values for lsmsvgfilterprimitive.go.
var GTypeSVGFilterPrimitive = externglib.Type(C.lsm_svg_filter_primitive_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypeSVGFilterPrimitive, F: marshalSVGFilterPrimitive},
	})
}

// SVGFilterPrimitiveOverrider contains methods that are overridable.
type SVGFilterPrimitiveOverrider interface {
	// The function takes the following parameters:
	//
	//    - view
	//    - input
	//    - output
	//    - subregion
	//
	Apply(view *SVGView, input, output string, subregion *Box)
}

type SVGFilterPrimitive struct {
	_ [0]func() // equal guard
	SVGElement
}

var (
	_ SVGElementer = (*SVGFilterPrimitive)(nil)
)

// SVGFilterPrimitiver describes types inherited from class SVGFilterPrimitive.
//
// To get the original type, the caller must assert this to an interface or
// another type.
type SVGFilterPrimitiver interface {
	externglib.Objector
	baseSVGFilterPrimitive() *SVGFilterPrimitive
}

var _ SVGFilterPrimitiver = (*SVGFilterPrimitive)(nil)

func classInitSVGFilterPrimitiver(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

	goval := gbox.Get(uintptr(data))
	pclass := (*C.LsmSvgFilterPrimitiveClass)(unsafe.Pointer(gclassPtr))
	// gclass := (*C.GTypeClass)(unsafe.Pointer(gclassPtr))
	// pclass := (*C.LsmSvgFilterPrimitiveClass)(unsafe.Pointer(C.g_type_class_peek_parent(gclass)))

	if _, ok := goval.(interface {
		Apply(view *SVGView, input, output string, subregion *Box)
	}); ok {
		pclass.apply = (*[0]byte)(C._gotk4_lasem0_SvgFilterPrimitiveClass_apply)
	}
}

//export _gotk4_lasem0_SvgFilterPrimitiveClass_apply
func _gotk4_lasem0_SvgFilterPrimitiveClass_apply(arg0 *C.LsmSvgFilterPrimitive, arg1 *C.LsmSvgView, arg2 *C.char, arg3 *C.char, arg4 *C.LsmBox) {
	goval := externglib.GoPrivateFromObject(unsafe.Pointer(arg0))
	iface := goval.(interface {
		Apply(view *SVGView, input, output string, subregion *Box)
	})

	var _view *SVGView  // out
	var _input string   // out
	var _output string  // out
	var _subregion *Box // out

	_view = wrapSVGView(externglib.Take(unsafe.Pointer(arg1)))
	_input = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))
	_output = C.GoString((*C.gchar)(unsafe.Pointer(arg3)))
	_subregion = (*Box)(gextras.NewStructNative(unsafe.Pointer(arg4)))

	iface.Apply(_view, _input, _output, _subregion)
}

func wrapSVGFilterPrimitive(obj *externglib.Object) *SVGFilterPrimitive {
	return &SVGFilterPrimitive{
		SVGElement: SVGElement{
			DOMElement: DOMElement{
				DOMNode: DOMNode{
					Object: obj,
				},
			},
		},
	}
}

func marshalSVGFilterPrimitive(p uintptr) (interface{}, error) {
	return wrapSVGFilterPrimitive(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

func (self *SVGFilterPrimitive) baseSVGFilterPrimitive() *SVGFilterPrimitive {
	return self
}

// BaseSVGFilterPrimitive returns the underlying base object.
func BaseSVGFilterPrimitive(obj SVGFilterPrimitiver) *SVGFilterPrimitive {
	return obj.baseSVGFilterPrimitive()
}

// The function takes the following parameters:
//
func (self *SVGFilterPrimitive) Apply(view *SVGView) {
	var _arg0 *C.LsmSvgFilterPrimitive // out
	var _arg1 *C.LsmSvgView            // out

	_arg0 = (*C.LsmSvgFilterPrimitive)(unsafe.Pointer(externglib.InternObject(self).Native()))
	_arg1 = (*C.LsmSvgView)(unsafe.Pointer(externglib.InternObject(view).Native()))

	C.lsm_svg_filter_primitive_apply(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(view)
}
